### ISSUE TITLE
Points instead of mesh and failed autoimport. Blender 4.0

### ISSUE THREAD

**Issue by RoySobak** [JoseConseco/GoB#431]
1. Create sphere in Blender.
2. Export it in Zbrush.
3. Smooth or sculpt sphere with Sculptris Pro Mode.
4. Import back in Blender.

Issues:
1. Doesn't import automatically.
2. If imported manually gives an error.
3. Manual import results in points without polygons.
![image](https://github.com/JoseConseco/GoB/assets/37121426/21e6a397-b19a-4de5-bd5f-8e4b7bfad4a6)
![image](https://github.com/JoseConseco/GoB/assets/37121426/ad3e2ef2-ba93-4d02-baaf-1131aba21a9c)

**Comment by kromar** [comment]
https://github.com/kromar/blender_GoB/tree/update-for-blender-4
Can you try this version? It should fix the import issue.

**Comment by RoySobak** [comment]
> https://github.com/kromar/blender_GoB/tree/update-for-blender-4 Can you try this version? It should fix the import issue.

I use exactly this version of GOB. It says so in error screenshot. But to be shure i redownloaded using this link and recreated steps above. Issue still there.

**Comment by kromar** [comment]
@RoySobak this is a issue with the latest alpha builds, to avoid this use a older build or wait for a build with a fix for this.
https://projects.blender.org/blender/blender/issues/111117
